### ISSUE TITLE
Support for DICOM sequence data

### ISSUE THREAD

**Issue by jas88** [HicServices/RdmpDicom#380]
Currently we map simple DICOM tag/value pairs such as PatientID to database columns. Ideally we need an analogous capability for coding sequences as used for ICD11 diagnostic findings, Fitzpatrick skin type in dermatology imaging and similar.

**Comment by rkm** [comment]
We have some support for tag "elevation" (if I remember the term correctly), but I agree there's probably an improvement we can make for sub-sequences with some known structure

**Comment by jas88** [comment]
Implemented in #393
