### ISSUE TITLE
NuspecIsCorrectTests only checking one csproj file

### ISSUE THREAD

**Issue by jas88** [HicServices/RdmpDicom#41]
Same issue as FAnsiSql? Plugin/netcoreapp2.2/netcoreapp2.2.csproj isn't checked against nuspec by NuspecIsCorrectTests as far as I can see, might cause headaches?

**Comment by tznind** [comment]
Hmn these are completely empty projects that exist only to build the relevant framework when combined with the nuspec so shouldn't need to be included...
