### ISSUE TITLE
Option to extract metadata only when using FoDicomAnonymizer [Zsolt]

### ISSUE THREAD

**Issue by tznind** [HicServices/RdmpDicom#64]
Skip writting the images to disk but still output the metadata file.

Large image extractions take many hours to run due to extracting the images.

It would save a large amount of time and effort if the images could be excluded when they are not required, I.e. second runs of the extraction, when the images are already extracted, but the data files need to be re-extracted.
[~skrueger001][~chall] Solving this issue will help DLS to release Imaging Data more quickly.

**Comment by RoyMudie** [comment]
Duplicated in JIRA - RDMPSUP-133

**Comment by RoyMudie** [comment]
Roy Mudie added a comment - Yesterday 10:00 AM
Example: mistakenly missed a column on extraction or column needs de-identified correctly means whole dataset needs extracted again.

**Comment by tznind** [comment]
Workaround exists to use the lookup mapping directly with `ColumnSwapper` component.

Only works for images that have already been extracted before.  Although theres a workaround for **that** which is to populate the lookup table before extraction.

**Comment by tznind** [comment]
Can be relaxed about missing columns (e.g. SOPInstanceUID)
