### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by tznind** [HicServices/RdmpDicom#82]
**Describe the bug**
One of the load components (probably AutoRoutingAttacher) seems to leak memory when running for long periods of time with many thousands of dicom files.  This issue is manifests in SmiServices and in RDMP client (in HIC).

**Screenshots**
![image](https://user-images.githubusercontent.com/31306100/93735909-7acc3d80-fbd6-11ea-9916-a67dc78188aa.png)

**RDMP.Dicom Plugin Version**
2.1.11

**RDMP Version**
4.1.9

**Comment by tznind** [comment]
So I ran the DLE for ~500 hours runtime locally and it clocked up to 3GB of RAM.  It didn't go down even after the DLE was finished and tab was closed which makes me think it must be fo-dicom

**Comment by jas88** [comment]
Might be a job for dot-Trace's detective skills?

**Comment by tznind** [comment]
> Might be a job for dot-Trace's detective skills?

Yeah assuming we can reproduce the issue in a test environment.  Getting dot-Trace to work in the VDI would probably be a struggle not to mention only currently having the release binaries to work with.

**Comment by jas88** [comment]
Yes, better to try to reproduce in a test environment I think - if we can reproduce even a small leak with some public test/dummy data that should be enough to get dotTrace on the trail. Probably a 1kb buffer somewhere that's getting leaked on each file, times 13m = 13 GB gone - so we just need to find the 1kb that leaks on 1 file somehow.

**Comment by tznind** [comment]
After loading 500 images (80 tags per image) 

![image](https://user-images.githubusercontent.com/31306100/93865030-a1b16f00-fcbd-11ea-8618-e4b04a875bfe.png)

**Comment by rkm** [comment]
Might be related: https://github.com/fo-dicom/fo-dicom/issues/1117

**Comment by tznind** [comment]
![image](https://user-images.githubusercontent.com/31306100/97284703-4719ae80-1839-11eb-898d-61e19e1cbbe8.png)

This is after 1 week of uptime of the microservices.  At no point does it run out of memory so not sure this is really a memory leak in the traditional sense.  VIRT memory usage is consistent with the other processes (Reprocessor and IdentifierMapper).  Only RES is high.  

I am also unable to reproduce this issue with the local feed anymore, now that process runs ~250MB of RAM and never grows despite running all day.

Unless anyone can investigate this further I will close it as a non issue or unrelated to the Rdmp.Dicom repo specifically.

**Comment by jas88** [comment]
With a memory leak I'd expect to see VIRT increasing but RES staying constant (because the leaked memory isn't active); slowly increasing RES may indicate something like a cache/lookup table slowly growing over time (fragmentation or adding new entries). Once the current develop branch of SmiServices goes live somewhere we can monitor and any genuine leak should be more apparent, thanks to the hourly cleanup. RES is the current "active" memory footprint, VIRT is the total including inactive.

**Comment by tznind** [comment]
Closing because this seems like environmental issue not code.
